data = [
    {
        "position": "RM",
        "name": "Xisco García",
        "goals": 14,
        "assists": 18,
        "yellow_cards": 0,
        "red_cards": 0,
        "age":20,
        "save": 0,
        "MOTMs": 5,
        "appearances": 38
    },
    {
        "position": "RB",
        "name": "Jeremie Frimpong",
        "goals": 1,
        "assists": 1,
        "yellow_cards": 2,
        "red_cards": 0,
        "save": 0,
        "age":24,
        "MOTMs": 1,
        "appearances": 44
    },
    {
        "position": "RW",
        "name": "Antony",
        "goals": 8,
        "assists": 3,
        "yellow_cards": 1,
        "red_cards": 0,
        "save": 0,
        "age":25,
        "MOTMs": 3,
        "appearances": 25
    },
    {
        "position": "LB",
        "name": "Bernd Janssen",
        "goals": 1,
        "assists": 2,
        "yellow_cards": 2,
        "red_cards": 0,
        "age":20,
        "save": 0,
        "MOTMs": 2,
        "appearances": 13
    },
    {
        "position": "CAM / CF",
        "name": "Mason Mount",
        "goals": 19,
        "assists": 24,
        "yellow_cards": 6,
        "red_cards": 0,
        "age":26,
        "save": 0,
        "MOTMs": 4,
        "appearances": 48
    },
    {
        "position": "LW",
        "name": "Alejandro Garnacho",
        "goals": 14,
        "assists": 12,
        "yellow_cards": 3,
        "red_cards": 0,
        "save": 0,
        "age":20,
        "MOTMs": 4,
        "appearances": 46
    },
    {
        "position": "CF",
        "name": "Bernardo Costa",
        "goals": 21,
        "assists": 10,
        "yellow_cards": 3,
        "red_cards": 0,
        "age":20,
        "save": 0,
        "MOTMs": 4,
        "appearances": 31
    },
    {
        "position": "CB",
        "name": "Lisandro Martínez",
        "goals": 1,
        "assists": 1,
        "yellow_cards": 3,
        "age" : 27,
        "red_cards": 0,
        "save": 0,
        "MOTMs": 2,
        "appearances": 43
    },
    {
        "position": "LB / CB",
        "name": "Joško Gvardiol",
        "goals": 3,
        "assists": 1,
        "yellow_cards": 6,
        "red_cards": 1,
        "age": 23,
        "save": 0,
        "MOTMs": 1,
        "appearances": 52
    },
    {
        "position": "CM",
        "name": "Frenkie de Jong",
        "goals": 18,
        "assists": 27,
        "yellow_cards": 6,
        "red_cards": 2,
        "age":28,
        "save": 0,
        "MOTMs": 5,
        "appearances": 55
    },
    {
        "position": "CB",
        "name": "Gonzalo Santana",
        "goals": 1,
        "assists": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "age":20,
        "save": 0,
        "MOTMs": 2,
        "appearances": 13
    },
    {
        "position": "ST",
        "name": "Rasmus Højlund",
        "goals": 30,
        "assists": 8,
        "yellow_cards": 0,
        "red_cards": 0,
        "save": 0,
        "age":22,
        "MOTMs": 4,
        "appearances": 35
    },
    {
        "position": "CAM / CM",
        "name": "Martin Ødegaard",
        "goals": 6,
        "assists": 12,
        "yellow_cards": 3,
        "red_cards": 0,
        "age":26,
        "save": 0,
        "MOTMs": 0,
        "appearances": 46
    },
    {
        "position": "RW / CAM",
        "name": "Paco Orozco",
        "goals": 17,
        "assists": 8,
        "yellow_cards": 6,
        "age": 17,
        "red_cards": 0,
        "save": 0,
        "MOTMs": 3,
        "appearances": 33
    },
    {
        "position": "CM / CDM",
        "name": "Kobbie Mainoo",
        "goals": 4,
        "assists": 7,
        "yellow_cards": 5,
        "red_cards": 0,
        "save": 0,
        "MOTMs": 0,
        "age" : 20,
        "appearances": 44
    },
    {
        "position": "CF",
        "name": "Óscar Araujo",
        "goals": 1,
        "assists": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "save": 0,
        "MOTMs": 0,
        "age":18,
        "appearances": 5
    },
    {
        "position": "CM",
        "name": "Stipe Jovanović",
        "goals": 0,
        "assists": 7,
        "yellow_cards": 2,
        "red_cards": 0,
        "save": 0,
        "MOTMs": 0,
        "age" : 20,
        "appearances": 34
    },
    {
        "position": "CDM / CB",
        "name": "Yanis Petit",
        "goals": 0,
        "assists": 2,
        "yellow_cards": 3,
        "red_cards": 0,
        "save": 0,
        "age" : 18,
        "MOTMs": 0,
        "appearances": 22
    },
    {
        "position": "CB",
        "name": "Matthijs de Ligt",
        "goals": 9,
        "assists": 0,
        "yellow_cards": 3,
        "red_cards": 0,
        "save": 0,
        "age":25,
        "MOTMs": 2,
        "appearances": 49
    }
]